### ISSUE TITLE
gemfile issue

### ISSUE THREAD

**Issue by williamhancharek** [learn-co-curriculum/flatiron-bnb-associations#11]
after running the commands:
`bundle install`
`learn`

There was an issue with the gemfile specification.  Short story is I fixed it by having the gemfile.lock require spring 2.0.2 instead of 1.3.3.  However, I don't think this error was meant to be a part of the learning process.

 I received the following error:
```
`WARN: Unresolved specs during Gem::Specification.reset:
      activesupport (>= 4.2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:317:in `check_for_activated_spec!': You have already activated spring 2.0.2, but your Gemfile requires spring 1.3.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:32:in `block in setup'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `map'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `setup'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/setup.rb:9:in `<top (required)>'
	from /home/williamhancharek/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /home/williamhancharek/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/spring-2.0.2/lib/spring/commands.rb:33:in `<module:Spring>'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/spring-2.0.2/lib/spring/commands.rb:4:in `<top (required)>'
	from /home/williamhancharek/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/williamhancharek/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/spring-2.0.2/lib/spring/server.rb:9:in `<top (required)>'
	from /home/williamhancharek/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /home/williamhancharek/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /home/williamhancharek/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/home/williamhancharek/Documents/learn/flatiron-bnb-associations-cb-000/spec/models/city_spec.rb:3:in `<top (required)>': uninitialized constant City (NameError)
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `load'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `each'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:97:in `setup'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:85:in `run'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:70:in `run'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:38:in `invoke'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.2.1/exe/rspec:4:in `<top (required)>'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `<main>'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/williamhancharek/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```
`

**Comment by maxwellbenton** [comment]
Hi @williamhancharek,

We have updated the Gemfile for this lab early last year and again this Spring believe this issue is resolved. Thank you for opening this and contributing to a Learn.co lesson!
